version: '3.9'

services:
  api:  
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyAppDb;User=sa;Password=Your_password123;Encrypt=True;TrustServerCertificate=True
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - devnetwork
    restart: unless-stopped
    
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - devnetwork
    restart: unless-stopped
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_password123 -N -C -Q \"SELECT 1\""
      ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sqlvolume:
    
networks:
  devnetwork:
    driver: bridge