# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  api:
    build:
      context: "C:\\Users\\mdiachok\\RiderProjects\\WebApplication1"
      dockerfile: "WebApplication1/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebApplication1.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapplication1:dev"
    ports: []
    volumes:
    - "C:\\Users\\mdiachok\\RiderProjects\\WebApplication1\\WebApplication1:/app:rw"
    - "C:\\Users\\mdiachok\\RiderProjects\\WebApplication1:/src:rw"
    - "C:\\Users\\mdiachok\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
