# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  api:
    build:
      context: "C:\\Users\\mdiachok\\RiderProjects\\WebApplication1"
      dockerfile: "WebApplication1/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "webapplication1:dev"
    ports:
    - "127.0.0.1:57002:57000"
    - "127.0.0.1:57202:57200"
    - "127.0.0.1:57402:57400"
    volumes:
    - "C:\\Users\\mdiachok\\RiderProjects\\WebApplication1\\WebApplication1:/app:rw"
    - "C:\\Users\\mdiachok\\RiderProjects\\WebApplication1:/src:rw"
    - "C:\\Users\\mdiachok\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\mdiachok\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.6\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.1.4\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\mdiachok\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_4_01_10_57_24:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
